[project]
name = "iemode-dl-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "comtypes>=1.4.15",
    "flask>=3.1.2",
    "pywinauto>=0.6.9",
    "selenium>=4.40.0",
]
